#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 25 12:04:20 2020

@author: Mac
"""


import numpy as np
import pandas as pd
import neuroseries as nts
from wrappers import *
from pylab import *
import os, sys
from functions import *
from pycircstat.tests import rayleigh
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from astropy.visualization import hist

import seaborn as sns
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
###############################################################
# PARAMETERS
###############################################################
data_directory='/Volumes/MyBook/EphysData/Experiments/200824/KA71-200824/KA71-200824'


episodes= ['sleep','wake','wake','wake','wake']#Modify this to suite the conditions you ave
events=['1','2','3','4'] #ids into the csvs in chro
n_analogin_channels = 2
channel_optitrack=1 #calls the second opened ch
spikes,shank= loadSpikeData(data_directory) #shank tells the number of cells on each shank
n_channels, fs, shank_to_channel = loadXML(data_directory)  #shank to channel 
position= loadPosition(data_directory,events,episodes,n_analogin_channels,channel_optitrack)
wake_ep=loadEpoch(data_directory,'wake',episodes)
sleep_ep=loadEpoch(data_directory,'sleep',episodes)


acceleration	= loadAuxiliary(data_directory, 1)  #mov't
newsleep_ep 	= refineSleepFromAccel(acceleration, sleep_ep)


if not os.path.exists(os.path.join(data_directory,'.eeg')):
		downsampleDatFile(os.path.join(data_directory))


